package com.example.homeMenu.model

import android.os.Parcelable
import androidx.annotation.NonNull
import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.parcelize.Parcelize
import kotlinx.serialization.Serializable

@Entity(tableName = "dishes")
@Serializable
@Parcelize
data class Dish(
    @PrimaryKey(autoGenerate = true)
    @NonNull
    @ColumnInfo(name = "dishId")
    val id: Int = 0,
    @ColumnInfo(name = "dishName")
    var name: String = "",
    @ColumnInfo(name = "dishType")
    var type: String = "",
    @ColumnInfo(name = "dishImage")
    @Serializable(with = UrlEncodedStringSerializer::class)
    var imageUrl: String = "",
    @ColumnInfo(name = "dishRecipe")
    @Serializable(with = UrlEncodedStringSerializer::class)
    var recipeLink: String = "",
    var isFavorite: Boolean = false,
    var rating: Int = 0,
) : Parcelable

var idNumber: Int = 1
var dishPost: Int = 3

var dishes =
    listOf(
        Dish(
            id = idNumber++,
            name = "Сливочный супчик с красной рыбкой",
            type = "Супы",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/54/8b/43142/sup-iz-krasnoi-ryby-so-slivkami_1645865140_0_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Сливочный супчик",
            type = "Супы",
            imageUrl = "https://i.obozrevatel.com/food/recipemain/2019/3/4/we.jpg?",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Грибной суп",
            type = "Супы",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/78/2a/18882/legkii-gribnoi-sup-s-vermishelu_1603697003_15_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Грибной крем - суп",
            type = "Супы",
            imageUrl = "https://klopotenko.com/wp-content/uploads/2018/03/gribnoi-krem-sup_siteweb-1000x600.jpg?",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Том Ям",
            type = "Супы",
            imageUrl = "https://klopotenko.com/wp-content/uploads/2018/03/tom-yam_siteweb-1-1000x600.jpg?",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Куриный крем - суп",
            type = "Супы",
            imageUrl = "https://static.1000.menu/img/content-v2/8e/95/42428/kurinyi-krem-sup-na-bulone-so-slivkami_1618076529_7_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Рамэн",
            type = "Супы",
            imageUrl = "https://klopotenko.com/wp-content/uploads/2023/12/ramen-z-kurkoyu-img-1000x600.jpg?",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Грибной крем - суп",
            type = "Супы",
            imageUrl = "https://klopotenko.com/wp-content/uploads/2018/11/Krem-sup-iz-shampinionov_site-web.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Натуральный лимонад",
            type = "Напитки",
            imageUrl = "https://klopotenko.com/wp-content/uploads/2018/05/Limonad-s-tarhunom_siteNewWeb.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Сливочное пиво",
            type = "Напитки",
            imageUrl = "https://cdn.segodnya.ua/i/image_1080x/media/image/61b/ddf/495/61bddf495e31c.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Смузи",
            type = "Напитки",
            imageUrl = "https://golden-flamingo.com.ua/wp-content/uploads/2023/06/5-frozen-fruit-smoothies-copy.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Лимонад из киви и цитрусов",
            type = "Напитки",
            imageUrl = "https://i.ytimg.com/vi/4yZYam3u8DY/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Горячий шоколад со взбитыми сливками",
            type = "Напитки",
            imageUrl = "https://img.freepik.com/premium-photo/hot-chocolate-with-whipped-cream_90258-2231.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Салат с сухариками",
            type = "Салаты",
            imageUrl = "https://ukr.media/static/ba/aimg/3/8/2/382470_1.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Вкусный салат из 4-х ингредиентов",
            type = "Салаты",
            imageUrl = "https://optim.tildacdn.one/tild6365-3832-4332-a565-313839623566/-/resize/744x/-/format/webp/1_.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Шампиньоны на гарнир",
            type = "Салаты",
            imageUrl = "https://i.ytimg.com/vi/z2UbCM_l6jE/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Полезный салат за копейки",
            type = "Салаты",
            imageUrl = "https://static.1000.menu/img/content-v2/78/43/34429/salat-svekla-s-chesnokom-i-greckim-orexom_1640164034_11_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Маринованные шампиньоны",
            type = "Салаты",
            imageUrl = "https://static.1000.menu/img/content-v2/bf/dd/4342/marinovannye-shampinony_1589539785_7_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Салат с сухариками № 2",
            type = "Салаты",
            imageUrl = "https://static.1000.menu/img/content-v2/c4/af/13180/salat-fasol-suxariki-kolbasa_1588657080_9_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + ((dishPost++) - 21 + dishPost++).toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Маринованные шампиньоны № 2",
            type = "Салаты",
            imageUrl = "https://treska.com.ua/wp-content/uploads/2018/03/IMG_0670got.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Ленивые сосиски в тесте",
            type = "Закуски",
            imageUrl = "https://i.ytimg.com/vi/Ij6Iz5opX_8/sddefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Сендвич в хлебе",
            type = "Завтрак",
            imageUrl = "https://sovkusom.ru/wp-content/uploads/recepty/s/sendvich-v-hlebe/thumb.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Сухарики",
            type = "Закуски",
            imageUrl = "https://static.1000.menu/img/content-v2/6c/a1/4757/chesnochnye-suxariki-s-chesnokom_1604986909_17_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Ленивый сендвич",
            type = "Завтрак",
            imageUrl = "https://i.pinimg.com/736x/f6/17/17/f61717905a0bf7235e3891f07f30e7fc.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Сендвич",
            type = "Завтрак",
            imageUrl = "https://static.1000.menu/img/content-v2/af/5d/38399/sendvich-s-vetchinoi_1616239118_15_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
        ),
        Dish(
            id = idNumber++,
            name = "Сендвич с яйцом",
            type = "Завтрак",
            imageUrl = "https://i.obozrevatel.com/food/recipemain/2019/3/19/po1.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Сырные крокеты",
            type = "Закуски",
            imageUrl = "https://i.obozrevatel.com/food/recipemain/2019/12/23/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Треугольники",
            type = "Закуски",
            imageUrl = "https://static.1000.menu/img/content-v2/97/e6/40973/treugolniki-iz-lavasha-s-syrom-na-skovorode_1616058344_13_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Картофель фри без жарки в масле",
            type = "Гарнир",
            imageUrl = "https://i.ytimg.com/vi/KrIdkF3qE1g/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Бургеры",
            type = "Гарнир",
            imageUrl = "https://mliesl.edu/contents/wp-content/uploads/2022/11/image5.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Крабовые снеки",
            type = "Закуски",
            imageUrl = "https://i.lefood.menu/wp-content/uploads/w_images/2021/09/recept-6831-1240x827_w.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Закуска",
            type = "Закуски",
            imageUrl = "https://2recepta.com/recept/grenki-s-chesnokom-i-syrom/grenki-s-chesnokom-i-syrom.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Картошка фри",
            type = "Гарнир",
            imageUrl = "https://img.delo-vcusa.ru/2023/02/kartoshka-fried-kak-v-mcdonalds.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Крабовые шарики",
            type = "Закуски",
            imageUrl = "https://static.1000.menu/img/content-v2/61/8b/471/syrnye-shariki-iz-krabovyx-palochek_1662097749_15_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Картошка в панировке",
            type = "Гарнир",
            imageUrl = "https://i.ytimg.com/vi/27P5HNX3DQ0/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Рулетики из баклажанов",
            type = "Закуски",
            imageUrl = "https://static.1000.menu/img/content-v2/a7/16/13812/ruletiki-iz-baklajanov-s-orexami-i-syrom_1628838164_13_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Рулет с красной рыбкой",
            type = "Закуски",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/23/b7/40265/rulet-iz-ryby-s-syrom_1572526888_7_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Шампиньоны на гарнир",
            type = "Закуски",
            imageUrl = "https://i.ytimg.com/vi/VnzFusnT9wo/hq720.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Горячий бутерброд на максималках",
            type = "Завтрак",
            imageUrl = "https://i.ytimg.com/vi/pH-KeghviVg/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Грибное сливочное масло",
            type = "Закуски",
            imageUrl = "https://i.ytimg.com/vi/n9zYVyzXMYI/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + (dishPost++) + ((dishPost++) - 44).toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Домашний хлеб «Чиабатта»",
            type = "Закуски",
            imageUrl = "https://i.ytimg.com/vi/aIbWI6oUW18/hq720.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Ленивая пицца",
            type = "Закуски",
            imageUrl = "https://static.1000.menu/img/content/35272/mini-picca-na-batone-v-duxovke_1559062077_11_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Лаваш с начинками",
            type = "Закуски",
            imageUrl = "https://i.ytimg.com/vi/J0Eb30LaznU/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + ((dishPost++) + (dishPost++) + (dishPost++) + (dishPost++) + (dishPost++) - 193).toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Сэндвич из сыра и бекона",
            type = "Завтрак",
            imageUrl = "https://i.ytimg.com/vi/fd1ylR80198/sddefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/" + dishPost++.toString(),
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Хлопковый бисквит",
            type = "Десерты",
            imageUrl = "https://static.1000.menu/img/content-v2/79/3f/20353/yaponskii-biskvit-kastella_1613028183_20_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/124",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Шоколадный десерт",
            type = "Десерты",
            imageUrl = "https://i.obozrevatel.com/food/recipemain/2023/6/7/848ed8e2-2072-45d4-b8e9-2ccab4406343.jpg",
            recipeLink = "https://t.me/obedkakdoma/126",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Испанский чизкейк",
            type = "Десерты",
            imageUrl = "https://static.1000.menu/img/content-v2/a8/cf/50324/ispanskii-chizkeik-svyatogo-sebastyana_1600538345_12_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/128",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Лимонный пирог",
            type = "Десерты",
            imageUrl = "https://images.unian.net/photos/2020_05/thumb_files/400_0_1589971479-7095.jpg",
            recipeLink = "https://t.me/obedkakdoma/129",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Банановый пудинг",
            type = "Десерты",
            imageUrl = "https://static.1000.menu/img/content-v2/d6/12/61623/bananovyi-puding_1641414107_15_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/130",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Творожная запеканка с смородиной",
            type = "Десерты",
            imageUrl = "https://i.ytimg.com/vi/2Zm9c6RgRgU/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/131",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Имбирные пряники",
            type = "Десерты",
            imageUrl = "https://yasensvit.ua/uploads/recipes/prev/634d8825d8bb7.jpg",
            recipeLink = "https://t.me/obedkakdoma/132",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Имбирные пряники №2",
            type = "Десерты",
            imageUrl = "https://img.moyo.ua/img/news_desc/1671/167162_1639739162_0.jpg",
            recipeLink = "https://t.me/obedkakdoma/133",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Мандариновая «Панна - Кота»",
            type = "Десерты",
            imageUrl = "https://i.ytimg.com/vi/9mRQAcQjq7E/hqdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/135",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Чизкейк «Нью - Йорк»",
            type = "Десерты",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/2e/63/26665/chizkeik-nu-iork-klassicheskii_1630161417_0_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/136",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Кекс на сгущенке",
            type = "Десерты",
            imageUrl = "https://static.1000.menu/img/content/10583/keksik-na-sgushchenke-snezhinka-_1368640645_0_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/137",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Чизкейк «Нью - Йорк» №2",
            type = "Десерты",
            imageUrl = "https://art-lunch.ru/content/uploads/2014/08/cheesecake-new-york-001x2-1.jpg",
            recipeLink = "https://t.me/obedkakdoma/138",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Шоколадные блинчики 3 в 1",
            type = "Десерты",
            imageUrl = "https://cdn.informator.ua/@prod/media/dnipro/2022/08/08/62f0ddbe2e211.jpg",
            recipeLink = "https://t.me/obedkakdoma/139",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Львівський сирник",
            type = "Десерты",
            imageUrl = "https://klopotenko.com/wp-content/uploads/2022/04/lvivskyy-syrnyk_sitewebukr-1000x600.jpg",
            recipeLink = "https://t.me/obedkakdoma/143",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Творожные сырки",
            type = "Десерты",
            imageUrl = "https://i.ytimg.com/vi/RxamcXMi1yI/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/147",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Блины «Рафаэло»",
            type = "Десерты",
            imageUrl = "https://ukranews.com/upload/news/2020/02/28/285e595822013b1-5e595811ab63f-recipe-b6f3681f-5b30-4aef-8462-008c2831c483-large_crop_1200.jpg",
            recipeLink = "https://t.me/obedkakdoma/148",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Банановый торт без выпечки",
            type = "Десерты",
            imageUrl = "https://static.1000.menu/img/content-v2/3c/46/57842/tort-iz-pechenya-smetany-i-bananov-bez-vypechki_1629264597_23_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/149",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Клубничное мороженое",
            type = "Десерты",
            imageUrl = "https://i.obozrevatel.com/food/recipemain/2019/1/22/9b560f81183e73fee4eef8eceb64a2d4klubnichnoyemorozhenoyedomadepositphot.jpg",
            recipeLink = "https://t.me/obedkakdoma/150",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Лимонный чизкейк",
            type = "Десерты",
            imageUrl = "https://i.ytimg.com/vi/TD4qWectVmY/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/119",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Банановый чизкейк без выпечки",
            type = "Десерты",
            imageUrl = "https://i.pinimg.com/736x/01/ff/e9/01ffe9f18cfbf858616c659033130833.jpg",
            recipeLink = "https://t.me/obedkakdoma/118",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Суфле з 2х ингредиентов",
            type = "Десерты",
            imageUrl = "https://i.ytimg.com/vi/ZKfn3B2G_cE/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/116",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Шоколадный десерт №2",
            type = "Десерты",
            imageUrl = "https://img-global.cpcdn.com/recipes/702df41a5b659c1c/680x482cq70/molochno-shokoladnyi-diesiert-%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%B5-%D1%84%D0%BE%D1%82%D0%BE-%D1%80%D0%B5%D1%86%D0%B5%D0%BF%D1%82%D0%B0.jpg",
            recipeLink = "https://t.me/obedkakdoma/114",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Печенье с джемом",
            type = "Десерты",
            imageUrl = "https://static.1000.menu/img/content-v2/3f/89/24204/pesochnoe-pechene-s-djemom_1617541906_11_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/99",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Банановые панкейки",
            type = "Завтрак",
            imageUrl = "https://static.1000.menu/img/content-v2/2b/4a/76165/bananovye-pankeiki-pp_1687677141_2_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/98",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Печенье с джемом №2",
            type = "Десерты",
            imageUrl = "https://kamelena.com/uploads/recipes/400/433/f433-pesochnoe-pechene-s-djemom.jpg",
            recipeLink = "https://t.me/obedkakdoma/97",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Ленивый Наполеон",
            type = "Десерты",
            imageUrl = "https://i.ytimg.com/vi/ia9JuLoSjjc/hq720.jpg",
            recipeLink = "https://t.me/obedkakdoma/110",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Клубничный тирамису",
            type = "Десерты",
            imageUrl = "https://golden-flamingo.com.ua/wp-content/uploads/2023/05/strawberry-tiramisu-ft-recipe0321-4148336bab854769a1a4af51cf39358f-1.jpg",
            recipeLink = "https://t.me/obedkakdoma/109",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Нежные творожники",
            type = "Десерты",
            imageUrl = "https://img-global.cpcdn.com/recipes/b04c6882f65b396b/680x482cq70/samyie-niezhnyie-tvorozhniki-v-rassypchatoi-korzinkie-%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%B5-%D1%84%D0%BE%D1%82%D0%BE-%D1%80%D0%B5%D1%86%D0%B5%D0%BF%D1%82%D0%B0.jpg",
            recipeLink = "https://t.me/obedkakdoma/108",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Суфле №2",
            type = "Десерты",
            imageUrl = "https://irecommend.ru/sites/default/files/product-images/343613/dbKS3IoX6BAjm0GcdvNMYg.jpg",
            recipeLink = "https://t.me/obedkakdoma/106",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Банановый чизкейк №2",
            type = "Десерты",
            imageUrl = "https://www.rbc.ua/static/img/f/r/freepik__com__32__1_1200x675.jpg",
            recipeLink = "https://t.me/obedkakdoma/103",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Шоколадное суфле",
            type = "Десерты",
            imageUrl = "https://static.1000.menu/img/content/12444/shokoladnoe-sufle_1422383159_0_max.JPG",
            recipeLink = "https://t.me/obedkakdoma/100",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Торт «Муравейник»",
            type = "Десерты",
            imageUrl = "https://i.obozrevatel.com/food/recipemain/2019/2/25/asp.jpg",
            recipeLink = "https://t.me/obedkakdoma/96",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Пирог Milka",
            type = "Десерты",
            imageUrl = "https://i.ytimg.com/vi/msGBbDcS3eQ/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/95",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Новогодние капкейки",
            type = "Десерты",
            imageUrl = "https://vsedeserti.ru/wp-content/uploads/2021/12/1-Novogodnie-kapkejki-na-2022-god-12-2.jpg",
            recipeLink = "https://t.me/obedkakdoma/94",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Творожная запеканка",
            type = "Десерты",
            imageUrl = "https://klopotenko.com/wp-content/uploads/2022/06/tvorozhnaya-zapekanka_siteweb-1000x600.jpg",
            recipeLink = "https://t.me/obedkakdoma/93",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Творожные трубочки к чаю",
            type = "Десерты",
            imageUrl = "https://i.ytimg.com/vi/a17WKgW3RkI/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/92",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Имбирные пряники №3",
            type = "Десерты",
            imageUrl = "https://apostrophe.ua/uploads/image/7c422092d662194b3eb17c761633a6b7.jpg",
            recipeLink = "https://t.me/obedkakdoma/91",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Трайфл «Черный принц»",
            type = "Десерты",
            imageUrl = "https://i.ytimg.com/vi/1kDtbglLecY/hq720.jpg",
            recipeLink = "https://t.me/obedkakdoma/90",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Торт «Птичье молоко»",
            type = "Десерты",
            imageUrl = "https://static.1000.menu/img/content-v2/d9/08/37893/tort-ptiche-moloko-po-gostu_1672412899_3_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/89",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Маковый рулет с творогом",
            type = "Десерты",
            imageUrl = "https://i.ytimg.com/vi/D3oa0LOe1qg/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/88",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Мандариновые мини-чизкейки без выпечки",
            type = "Десерты",
            imageUrl = "https://i.ytimg.com/vi/sNwSmXvdFAY/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/87",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Птичье молоко",
            type = "Десерты",
            imageUrl = "https://i.ytimg.com/vi/Gz_OuR8P49g/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/86",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Слаткие конверты",
            type = "Десерты",
            imageUrl = "https://smachnota.com.ua/images/flt/blinchiki-sladkie/1040-800-bliny-sladkie.jpg",
            recipeLink = "https://t.me/obedkakdoma/85",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Творожные сырки в шоколаде №2",
            type = "Десерты",
            imageUrl = "https://i.ytimg.com/vi/BYo9bkY75G0/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/84",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Нежный меренговый рулет",
            type = "Десерты",
            imageUrl = "https://i.ytimg.com/vi/hXyrcRbvnTc/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/83",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Кексы с кремом и карамелью",
            type = "Десерты",
            imageUrl = "https://i.ytimg.com/vi/nub05HqXbGA/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/82",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Шоколадный рулет с фруктами",
            type = "Десерты",
            imageUrl = "https://www.rbc.ua/static/img/5/6/5678_6_1300x820.jpg",
            recipeLink = "https://t.me/obedkakdoma/81",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Шоколадный рулет с фруктами",
            type = "Десерты",
            imageUrl = "https://www.rbc.ua/static/img/5/6/5678_6_1300x820.jpg",
            recipeLink = "https://t.me/obedkakdoma/81",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Очень ленивый Наполеон №2",
            type = "Десерты",
            imageUrl = "https://i.ytimg.com/vi/S3bwPf3lrUU/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/80",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Классический чизкейк Нью-Йорк №2",
            type = "Десерты",
            imageUrl = "https://yasensvit.ua/uploads/recipes/prev/639ca77703b3a.jpg",
            recipeLink = "https://t.me/obedkakdoma/79",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Медовик",
            type = "Десерты",
            imageUrl = "https://i.ytimg.com/vi/zn4bB7udHXY/sddefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/78",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Печенье Баунти",
            type = "Десерты",
            imageUrl = "https://realist.online/img/article/1148/68_main-v1643724687.jpg",
            recipeLink = "https://t.me/obedkakdoma/77",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Нежный рулет с фруктами №2",
            type = "Десерты",
            imageUrl = "https://static.1000.menu/img/content-v2/92/4f/19044/rulet-s-yablokami-v-duxovke_1679818737_14_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/76",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Творожные сладкие булочки",
            type = "Десерты",
            imageUrl = "https://static.1000.menu/img/content/35776/tvorojnye-bulochki-kak-pux-za-5-minut_1560363989_10_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/75",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "ПП Ватрушки",
            type = "Десерты",
            imageUrl = "https://static.1000.menu/img/content-v2/91/6b/87012/pp-vatrushki-s-tvorogom_1719038791_0_yb71z3s_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/74",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Творожные пончика",
            type = "Десерты",
            imageUrl = "https://static.1000.menu/img/content/25032/tvorojnye-ponchiki-klassicheskie_1516399344_1_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/73",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Кексы с рикоттой и малиной",
            type = "Десерты",
            imageUrl = "https://static.1000.menu/img/content/10992/keksj-s-malinoi-i-fundukom_1379011880_0_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/72",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Шоколадный кекс с чизкейком",
            type = "Десерты",
            imageUrl = "https://i.ytimg.com/vi/AI8zu_bTnuw/hq720.jpg",
            recipeLink = "https://t.me/obedkakdoma/71",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Бананово-кокосовые кексы",
            type = "Десерты",
            imageUrl = "https://ifs.cook-time.com/preview/img1010/1010583.jpg",
            recipeLink = "https://t.me/obedkakdoma/70",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Турецкий кекс",
            type = "Десерты",
            imageUrl = "https://static.1000.menu/img/content-v2/6e/bc/69579/tureckii-shokoladnyi-keks-mokryi_1668892294_15_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/69",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Турецкий кекс",
            type = "Десерты",
            imageUrl = "https://ifs.cook-time.com/preview/img1010/1010583.jpg",
            recipeLink = "https://t.me/obedkakdoma/69",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Воздушные японские панкейки",
            type = "Завтрак",
            imageUrl = "https://static.1000.menu/img/content-v2/36/ec/37561/yaponskie-pankeiki-pyshnye-vozdushnye-na-skovorode_1616599043_16_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/67",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Венский сырник",
            type = "Десерты",
            imageUrl = "https://dvazajci.com/wp-content/uploads/2020/12/7.jpg",
            recipeLink = "https://t.me/obedkakdoma/66",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Клубничное тирамису №2",
            type = "Десерты",
            imageUrl = "https://shuba.life/static/content/thumbs/1905x884/6/95/v3i3mc---c1905x884x50px50p-up--90caa610d34278bfb82120dc0af77956.jpg",
            recipeLink = "https://t.me/obedkakdoma/65",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Творожная запеканка №3",
            type = "Десерты",
            imageUrl = "https://static.1000.menu/img/content/35128/tvorojnaya-zapekanka-kak-v-detstve_1558702907_1_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/64",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Итальянский десерт крем-кофе",
            type = "Десерты",
            imageUrl = "https://i.ytimg.com/vi/ddjvT19Wu84/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/63",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Тирамису №3",
            type = "Десерты",
            imageUrl = "https://i.ytimg.com/vi/3gp50W4Rlm4/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/61",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Заварной пирожное",
            type = "Десерты",
            imageUrl = "https://i.ytimg.com/vi/9GZLEY1lKCU/hq720.jpg",
            recipeLink = "https://t.me/obedkakdoma/60",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Клубничная каша",
            type = "Завтрак",
            imageUrl = "https://i.ytimg.com/vi/Fd27OU6z2wc/sddefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/59",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Кофейное желе",
            type = "Десерты",
            imageUrl = "https://static.1000.menu/img/content/34313/molochno-kofeinoe-jele_1555635977_1_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/58",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Вкусные оладьи",
            type = "Завтрак",
            imageUrl = "https://static.1000.menu/img/content-v2/d3/e8/24736/oladi-ochen-pyshnye-na-kefire_1594324969_14_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/57",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Тирамису №4",
            type = "Десерты",
            imageUrl = "https://i0.wp.com/foxychef.ru/wp-content/uploads/2018/09/MG_52941.jpg",
            recipeLink = "https://t.me/obedkakdoma/56",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Моти",
            type = "Десерты",
            imageUrl = "https://bottva.ru/wp-content/uploads/2021/12/230114_daifuku_0.jpg",
            recipeLink = "https://t.me/obedkakdoma/55",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "ПП тирамису с бананом",
            type = "Десерты",
            imageUrl = "https://receptor.top/media/zoo/images/21211-1_dba2ff13f87cf7d0e694f5ff95f24b6e.jpg",
            recipeLink = "https://t.me/obedkakdoma/54",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Сырники",
            type = "Завтрак",
            imageUrl = "https://klopotenko.com/wp-content/uploads/2020/06/syrniki_klassicheskie_siteweb-1000x600.jpg",
            recipeLink = "https://t.me/obedkakdoma/53",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "7 Лучших коктейлей из cоулсов",
            type = "Напитки",
            imageUrl = "https://static.stratege.ru/trophies/NPWR07897_00/TROP016.PNG",
            recipeLink = "https://t.me/obedkakdoma/151",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Паста с курицей",
            type = "Гарнир",
            imageUrl = "https://img.inmyroom.ru/inmyroom/thumb/620x398/jpg:85/uploads/food_recipe/teaser/67/6735/jpg_1000_6735bd3f-f4ed-4121-bf47-41fb9a004987.jpg?sign=c3f504ba1939718580d2f37ada373c4b6655aae2fad797051133ecf5e39dd0be",
            recipeLink = "https://t.me/obedkakdoma/158",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Суши-торт",
            type = "Гарнир",
            imageUrl = "https://sushiman.kiev.ua/wp-content/uploads/2024/12/tort-sushi-1536x864.jpg",
            recipeLink = "https://t.me/obedkakdoma/159",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Онигири",
            type = "Закуски",
            imageUrl = "https://eda.ru/images/RecipePhoto/620x415/onigiri_186555_photo_194246.webp",
            recipeLink = "https://t.me/obedkakdoma/160",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Жареные пельмени",
            type = "Гарнир",
            imageUrl = "https://www.ermolino-produkty.ru/recipes/picts/recipes/tnw682-670%D1%85430_jarenie_pelmeni_scovorode.jpg",
            recipeLink = "https://t.me/obedkakdoma/161",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Жареные пельмени 2.0",
            type = "Гарнир",
            imageUrl = "https://www.ermolino-produkty.ru/recipes/picts/recipes/tnw682-670%D1%85430_jarenie_pelmeni_syrom.jpg",
            recipeLink = "https://t.me/obedkakdoma/162",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Шакшука",
            type = "Завтрак",
            imageUrl = "https://klopotenko.com/wp-content/uploads/2018/02/shakshuka-ili-yaichnica-po-arabski_siteWeb.jpg",
            recipeLink = "https://t.me/obedkakdoma/163",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Паста с томатами",
            type = "Гарнир",
            imageUrl = "https://barilla.ru/wp-content/uploads/2023/10/spagetti-s-tomatnym-sousom-i-bazilikom-e1718068401227.webp",
            recipeLink = "https://t.me/obedkakdoma/164",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Яблочное ризотто",
            type = "Завтрак",
            imageUrl = "https://static.wikia.nocookie.net/shokugekinosoma/images/5/5b/%D0%AF%D0%B1%D0%BB%D0%BE%D1%87%D0%BD%D0%BE%D0%B5_%D0%A0%D0%B8%D0%B7%D0%BE%D1%82%D1%82%D0%BE.png/revision/latest?cb=20191013102321&path-prefix=ru",
            recipeLink = "https://t.me/obedkakdoma/165",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Курица с рисом",
            type = "Гарнир",
            imageUrl = "https://volshebnaya-eda.ru/wp-content/uploads/2017/07/kurica-farshirovannaya-risom-10-810x540.jpg",
            recipeLink = "https://t.me/obedkakdoma/166",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Омлет в помидоре",
            type = "Завтрак",
            imageUrl = "https://zira.uz/wp-content/uploads/2018/11/pp-yayca-v-pomidore-4.jpg",
            recipeLink = "https://t.me/obedkakdoma/167",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Картофель в микроволновке",
            type = "Гарнир",
            imageUrl = "https://cdn.lifehacker.ru/wp-content/uploads/2020/01/shutterstock_1502271413_1580887100-e1580887205417-scaled-640x320.jpg",
            recipeLink = "https://t.me/obedkakdoma/168",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Куриное карри",
            type = "Гарнир",
            imageUrl = "https://static.vkusnyblog.com/img3x4/uploads/2019/10/karri-s-kuricei-i-percem.jpg",
            recipeLink = "https://t.me/obedkakdoma/169",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Настоящая оригинальная карбонара",
            type = "Гарнир",
            imageUrl = "https://images.unian.net/photos/2021_03/1615387932-9078.jpg?0.6738803825235229",
            recipeLink = "https://t.me/obedkakdoma/171",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Онигири",
            type = "Закуски",
            imageUrl = "https://images.gastronom.ru/UOF6tSWLpiUIb3dL05BLPLoqJ5dq7BbKe4mCgTtmzwI/pr:recipe-cover-image/g:ce/rs:auto:0:0:0/L2Ntcy9hbGwtaW1hZ2VzL2QxM2I5Y2UzLTBjNzEtNGU5Yi04NDIzLTI5NWYxOTY1YTYyZC5qcGc.webp",
            recipeLink = "https://t.me/obedkakdoma/172",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Картофель запечённый с капченым салом и соусом терияки",
            type = "Гарнир",
            imageUrl = "https://img1.russianfood.com/dycontent/images_upl/607/big_606288.jpg",
            recipeLink = "https://t.me/obedkakdoma/173",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Китайские драники",
            type = "Гарнир",
            imageUrl = "https://smachnonews.24tv.ua/resources/photos/news/202202/1863357.jpg?v=1661256692000&w=768&h=432&fit=cover&output=webp&q=70",
            recipeLink = "https://t.me/obedkakdoma/174",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Картофель на сковороде",
            type = "Гарнир",
            imageUrl = "https://img.iamcook.ru/2023/upl/recipes/cat/u-746ef5453db748d86dd60eefedd1a96f.jpg",
            recipeLink = "https://t.me/obedkakdoma/175",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Рататуй",
            type = "Гарнир",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/8f/59/17258/ratatui-iz-baklajanov_1623137185_1_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/176",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "«Не типова» шаурма",
            type = "Гарнир",
            imageUrl = "https://img1.russianfood.com/dycontent/images_upl/190/big_189903.jpg",
            recipeLink = "https://t.me/obedkakdoma/178",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Лепёшки с картофелем и сыром",
            type = "Закуски",
            imageUrl = "https://static.1000.menu/res/640/img/content/36611/kartofelnye-lepeshki-na-skovorode_1562774912_10_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/179",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Сочное буррито",
            type = "Гарнир",
            imageUrl = "https://static.1000.menu/img/content-v2/f1/67/15421/burrito-po-meksikanski_1676292399_3_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/180",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Пирог а-ля жульен",
            type = "Гарнир",
            imageUrl = "https://i.ytimg.com/vi/XjdkoscmCFM/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBSM45Gm2Kc05phF2ZYw500KWUrRw",
            recipeLink = "https://t.me/obedkakdoma/182",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Молодой картофель",
            type = "Гарнир",
            imageUrl = "https://klopotenko.com/wp-content/uploads/2020/06/Molodoi-kartofel-s-ykropom_siteWeb.jpg?v=1592918664",
            recipeLink = "https://t.me/obedkakdoma/183",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Куриные рулетики из лаваша",
            type = "Гарнир",
            imageUrl = "https://static.1000.menu/img/content/31396/rulet-iz-lavasha-s-kuricei-i-ovoshchami_1547567518_1_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/184",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Необычный, но очень вкусный завтрак",
            type = "Завтрак",
            imageUrl = "https://i.ytimg.com/vi/F5b6lVMbqIg/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAPjLSGK-tgMbMOIgVgA7mA4a2Tgg",
            recipeLink = "https://t.me/obedkakdoma/185",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Картофельные оладушки с сыром и кукурузой",
            type = "Завтрак",
            imageUrl = "https://static.1000.menu/img/content/22115/kartofelnye-oladi_1503779598_9_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/186",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Яйца пашот",
            type = "Завтрак",
            imageUrl = "https://static.1000.menu/res/640/img/content/22034/-yaico-pashot-yaico-pashot-ot-djeimi-olivera_1503417401_1_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/187",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Шакшука",
            type = "Завтрак",
            imageUrl = "https://tilly.by/wp-content/uploads/2017/09/SHakshuka2.jpg",
            recipeLink = "https://t.me/obedkakdoma/188",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Картофельные хот-доги",
            type = "Закуски",
            imageUrl = "https://foodee.top/media/zoo/images/422-7_fead3459ab6624513f8f712ba6c03c97.jpg",
            recipeLink = "https://t.me/obedkakdoma/189",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Очень вкусные макароны",
            type = "Гарнир",
            imageUrl = "https://theherbeevore.com/wp-content/uploads/2023/05/wp-1684808953872.jpg",
            recipeLink = "https://t.me/obedkakdoma/190",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Картофельный пирог с грибами",
            type = "Гарнир",
            imageUrl = "https://i.ytimg.com/vi/JbAcxoaviRI/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCiwGP3ErHLL2gAC80WrPAcuqvbgA",
            recipeLink = "https://t.me/obedkakdoma/191",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Картофельная запеканка на сковороде",
            type = "Гарнир",
            imageUrl = "https://static.1000.menu/res/640/img/content/21190/-zapekanka-na-skovorode-kartofelnaya-zapekanka-na-skovorode_1499559603_1_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/192",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Паста с морепродуктами",
            type = "Гарнир",
            imageUrl = "https://klopotenko.com/wp-content/uploads/2021/04/pasta-s-moreproduktami_siteweb-1-1000x600.jpg?v=1618941726",
            recipeLink = "https://t.me/obedkakdoma/193",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Арабские блинчики с грибами и сыром",
            type = "Закуски",
            imageUrl = "https://i0.wp.com/www.tvcook.ru/wp-content/uploads/images/topic/2020/02/20/0b96cf72bd-scaled.jpg?resize=680%2C270&ssl=1",
            recipeLink = "https://t.me/obedkakdoma/194",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Конвертики с курицей и сыром",
            type = "Закуски",
            imageUrl = "https://static.1000.menu/img/content-v2/29/5c/37831/sloenye-konvertiki-v-duxovke-s-syrom-kuricei-i-kartoshkoi_1645166633_5_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/195",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Картофельный гратен с грибами",
            type = "Гарнир",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/36/03/21764/graten-s-kuricei_1594882237_17_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/196",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Картошка в панировке",
            type = "Гарнир",
            imageUrl = "https://i.ytimg.com/vi/27P5HNX3DQ0/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/198",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Стожки с картофелем и сыром",
            type = "Гарнир",
            imageUrl = "https://static.1000.menu/img/content-v2/57/e0/28050/stojki-s-syrom-farshem-i-kartoshkoi_1643093756_15_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/199",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Картофельный рулет с фаршем",
            type = "Гарнир",
            imageUrl = "https://i.ytimg.com/vi/3o-2-n56J1M/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLC8xiwISFyMv6NbSyzyxP_EIxaLxA",
            recipeLink = "https://t.me/obedkakdoma/200",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Картофель с колбасками в духовке ",
            type = "Гарнир",
            imageUrl = "https://img.iamcook.ru/2020/upl/recipes/cat/u-f0892af9be4a4f45897a60bcb96606e3.jpg",
            recipeLink = "https://t.me/obedkakdoma/201",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Запеканка с овощами и курицей сыром",
            type = "Гарнир",
            imageUrl = "https://rud.ua/uploads/under_recipe/5%20shutterstock_582716332.jpg",
            recipeLink = "https://t.me/obedkakdoma/202",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Мексиканская энчилада с фаршем",
            type = "Гарнир",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/92/51/74/meksikanskaya-enchilada-s-farshem_1728120855_20_ccxzely_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/203",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Азиатский завтрак",
            type = "Завтрак",
            imageUrl = "",
            recipeLink = "",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Картофельный гратен",
            type = "Гарнир",
            imageUrl = "https://klopotenko.com/wp-content/uploads/2018/10/Graten-Dofinua_siteWeb.jpg",
            recipeLink = "https://t.me/obedkakdoma/205",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Турецкие лепёшки с творогом и зеленью",
            type = "Закуски",
            imageUrl = "https://i.ytimg.com/vi/sHrCdeaCS7w/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/206",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Экспресс хачапури",
            type = "Гарнир",
            imageUrl = "https://liza.ua/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2014/06/jollage.jpg.webp",
            recipeLink = "https://t.me/obedkakdoma/207",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Запеканка с овощами и куриной грудкой",
            type = "Гарнир",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/83/bd/45554/brokkoli-s-myasom-v-duxovke_1587061148_1_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/208",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Ризотто с креветками",
            type = "Гарнир",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/17/d1/41213/klassicheskoe-rizotto-s-moreproduktami_1631114536_1_max.jpg ",
            recipeLink = "https://t.me/obedkakdoma/211",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Фрунчоза",
            type = "Гарнир",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/fe/ee/41244/funchoza-s-kuricei-ovoshchami-i-soevym-sousom_1575458963_9_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/212",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Быстрая пицца",
            type = "Завтрак",
            imageUrl = "https://zira.uz/wp-content/uploads/2020/06/picca-na-skovorode.jpg",
            recipeLink = "https://t.me/obedkakdoma/215",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Булочка на завтрак",
            type = "Завтрак",
            imageUrl = "https://static.detivgorode.ua/files/blog/6567/398325-1.jpg",
            recipeLink = "https://t.me/obedkakdoma/216",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Слойка с сыром и колбасой",
            type = "Завтрак",
            imageUrl = "https://www.ermolino-produkty.ru/recipes/picts/recipes/tnw682-670%D1%85430_sloyki_kolbasoy.jpg",
            recipeLink = "https://t.me/obedkakdoma/217",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Жаренный рис с креветками",
            type = "Гарнир",
            imageUrl = "https://klopotenko.com/wp-content/uploads/2021/02/Ris-po-taiski_siteWeb.jpg?v=1612965868",
            recipeLink = "https://t.me/obedkakdoma/220",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Мидии в сливочном соусе",
            type = "Гарнир",
            imageUrl = "https://static.1000.menu/res/640/img/content/35063/midii-zamorojennye-v-slivochnom-souse_1558683789_1_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/221",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Стожки с картофелем и сыром",
            type = "Гарнир",
            imageUrl = "https://static.1000.menu/img/content-v2/57/e0/28050/stojki-s-syrom-farshem-i-kartoshkoi_1643093759_20_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/223",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Домашняя фунчоза",
            type = "Гарнир",
            imageUrl = "https://gotovim-doma.ru/images/recipe/a/1f/a1f424dbf64e52c31f69cd8645707fef_l.jpg",
            recipeLink = "https://t.me/obedkakdoma/224",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Сытные булочки",
            type = "Завтрак",
            imageUrl = "https://cdn.profile.ru/wp-content/uploads/2023/02/Yaichnica-v-bulochke-782x440.jpg",
            recipeLink = "https://t.me/obedkakdoma/225",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Паста",
            type = "Гарнир",
            imageUrl = "https://www.menslife.com/upload/iblock/e9d/italyanskaya_pasta_za_30_minut_samye_prostye_i_vkusnye_retsepty.jpg",
            recipeLink = "https://t.me/obedkakdoma/228",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Сочные «курники»",
            type = "Гарнир",
            imageUrl = "https://static.1000.menu/img/content-v2/93/29/46567/mini-kurniki-s-kuricei_1672327796_3_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/230",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Ленивая пицца",
            type = "Закуски",
            imageUrl = "https://static.1000.menu/res/640/img/content/13496/lenivaya-picca-iz-batona-v-duxovke_1435614589_0_max.JPG",
            recipeLink = "https://t.me/obedkakdoma/231",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Пибимпаб - корейский боул",
            type = "Гарнир",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/d5/fd/50843/koreiskii-pibimpab_1618595827_18_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/232",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Оладьи",
            type = "Завтрак",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/d3/1b/55993/vozdushnye-oladi-na-kefire-ochen-pyshnye_1624705380_15_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/233",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Куриная отбивная в кляре",
            type = "Мясо/Рыба",
            imageUrl = "https://prostokvashino.ru/upload/resize_cache/iblock/b73/800_800_0/b735e11834bd050a1a7121cf8da16868.jpg",
            recipeLink = "https://t.me/obedkakdoma/234",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Котлета по киевски",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/df/25/51020/kotlety-po-kievski-iz-kurinogo-farsha_1616069228_18_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/235",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Сочная куриная грудка",
            type = "Мясо/Рыба",
            imageUrl = "https://www.ermolino-produkty.ru/recipes/picts/recipes/tnw682-670%D1%85430_sochnaya-kurinaya-grudka-skovorode.jpg",
            recipeLink = "https://t.me/obedkakdoma/236",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Куриные ножки с картофелем",
            type = "Мясо/Рыба",
            imageUrl = "https://i.ytimg.com/vi/34Dwf_B9zTg/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLD4JXvPzRzG-N28WRLIiUAbZgavCw",
            recipeLink = "https://t.me/obedkakdoma/237",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Бефстроганов",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/08/7f/22223/befstroganov-iz-svininy-klassicheskii-s-tomatnoi-pastoi_1639816462_13_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/238",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Крылышки в духовке",
            type = "Мясо/Рыба",
            imageUrl = "https://images.unian.net/photos/2020_05/1590350938-7407.jpg?0.045633946482465326",
            recipeLink = "https://t.me/obedkakdoma/239",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Курочка на 10/10 в панировке",
            type = "Мясо/Рыба",
            imageUrl = "https://i.ytimg.com/vi/wI8vjCWagDg/hqdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/240",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Бефстроганов",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/d0/35/36199/befstroganov-so-slivkami_1614687128_14_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/241",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Сосиски в тесте \"Осьминожки\"",
            type = "Закуски",
            imageUrl = "https://static.1000.menu/res/640/img/content/24187/zakuska-iz-sosisok-osminojki_1511804763_11_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/242",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Курица с рисом",
            type = "Гарнир",
            imageUrl = "https://i.ytimg.com/vi/kAkFW0b-67A/sddefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/243",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Нагетсы",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/res/640/img/content/26431/naggetsy-na-skovorode_1522874970_13_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/244",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Котлета на косточке",
            type = "Мясо/Рыба",
            imageUrl = "https://i.ytimg.com/vi/38BzWXCz-N4/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/245",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Рыба на овощах",
            type = "Мясо/Рыба",
            imageUrl = "https://masterchef.kz/wp-content/uploads/2021/04/239-ryba-zapechennaja-s-ovoshhamii-0-1024x678.jpg",
            recipeLink = "https://t.me/obedkakdoma/246",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Жареные сарганы",
            type = "Мясо/Рыба",
            imageUrl = "https://storage.delikateska.ru/7/4/1de0ccf0-55fe-4633-888a-4be93f612464.jpg",
            recipeLink = "https://t.me/obedkakdoma/247",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Блинчики с рыбой",
            type = "Закуски",
            imageUrl = "https://volshebnaya-eda.ru/wp-content/uploads/2020/02/bliny-s-lososem-8.jpg",
            recipeLink = "https://t.me/obedkakdoma/248",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Суши",
            type = "Гарнир",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/59/d5/22172/rolly-filadelfiya-v-domashnix-usloviyax_1613551625_20_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/249",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Мясо с начинкой",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/img/content-v2/e9/a9/30973/myasnye-ruletiki-s-gribami-i-syrom_1610519117_13_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/250",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Бефстроганов",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/56/91/17756/befstroganov-klassicheskii_1584346789_9_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/251",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Нагетсы",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/e9/53/17052/kurinye-naggetsy-kak-v-makdonaldse_1607579003_14_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/252",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Пита с начинкой",
            type = "Гарнир",
            imageUrl = "https://static.1000.menu/res/640/img/content/29236/pita-s-nachinkoi-iz-kuricy_1540310803_1_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/253",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Сосиски в лаваше",
            type = "Закуски",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/70/21/15411/trubochki-c-mini-sosiskami_1588835312_8_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/254",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Сосиски-нагетсы",
            type = "Мясо/Рыба",
            imageUrl = "https://i.ytimg.com/vi/MLdw2j1KOzM/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBhdmS_6LCC5PgbuFoDAN37o9nqxA",
            recipeLink = "https://t.me/obedkakdoma/255",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Котлеты, а внутри яйцо",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/13/ad/29781/kotlety-s-yaicom-vnutri_1637401634_17_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/257",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Три вида маринада для шашлычков на шпажках",
            type = "Мясо/Рыба",
            imageUrl = "https://i.ytimg.com/vi/P-ropljlbqI/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCHeffdg0tlT2JzuK5gpsgLvPo6ug",
            recipeLink = "https://t.me/obedkakdoma/258",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Хрустящие ножки",
            type = "Мясо/Рыба",
            imageUrl = "https://static.tildacdn.com/tild3239-3231-4465-b962-366239396136/20210311_152041.jpg",
            recipeLink = "https://t.me/obedkakdoma/259",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Очень вкусные крылышки",
            type = "Мясо/Рыба",
            imageUrl = "https://i.ytimg.com/vi/ORSB-AE6g_Q/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLA9C-oP6eYy2CItOC5Ae26MjAKdQQ",
            recipeLink = "https://t.me/obedkakdoma/260",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Куриные рулетики",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/d7/71/15597/kurinyi-rulet-s-syrom-i-sladkim-percem_1682867853_0_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/261",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Очень вкусная рыбка",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/38/5f/62548/sudak-s-ovoschami-v-duxovke-zapechenyi_1644090011_1_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/262",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Мясо по-французски",
            type = "Гарнир",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/6e/e5/3957/kartoshka-po-frantsuzski-s-myasom_1614404930_11_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/263",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Курица по - азиатски",
            type = "Мясо/Рыба",
            imageUrl = "https://i.ytimg.com/vi/zlmQCMaEX4g/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/264",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Куриный рулет с грибами и сыром",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/4c/5b/11970/kurinyi-rulet-s-gribami-i-syrom_1609922769_22_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/265",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Курочка в луковом кляре",
            type = "Мясо/Рыба",
            imageUrl = "https://img-global.cpcdn.com/recipes/db2ca2c3110431b3/680x964cq70/kurinoie-filie-v-lukovom-kliarie-%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%B5-%D1%84%D0%BE%D1%82%D0%BE-%D1%80%D0%B5%D1%86%D0%B5%D0%BF%D1%82%D0%B0.webp",
            recipeLink = "https://t.me/obedkakdoma/266",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Очень сочное мясо",
            type = "Мясо/Рыба",
            imageUrl = "https://biznes-lanch.com/wa-data/public/photos/64/04/464/464.970.jpg",
            recipeLink = "https://t.me/obedkakdoma/267",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Куриная грудка с сырной начинкой ",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/ca/e9/20815/kurinaya-grudka-s-gribami-i-syrom-v-duxovke_1609905264_1_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/269",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Паровые булочки бао с мясом",
            type = "Закуски",
            imageUrl = "https://yasensvit.ua/uploads/recipes/prev/601bf9d0d667d.webp",
            recipeLink = "https://t.me/obedkakdoma/270",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Хрустящие куриные тендеры",
            type = "Мясо/Рыба",
            imageUrl = "https://cdn.shopify.com/s/files/1/0254/7715/2804/files/crispy_air_fried_chicken_long_1024x1024.jpg?v=1731334970",
            recipeLink = "https://t.me/obedkakdoma/271",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Сочная грудинка",
            type = "Мясо/Рыба",
            imageUrl = "https://www.ermolino-produkty.ru/recipes/picts/recipes/tnw682-670%D1%85430_sochnaya-kurinaya-grudka-skovorode.jpg",
            recipeLink = "https://t.me/obedkakdoma/272",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Греча с курицей",
            type = "Гарнир",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/6b/09/20102/grechka-po-kupecheski-s-kuricei_1625826675_1_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/273",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Куриное филе на овощной подушке",
            type = "Гарнир",
            imageUrl = "https://cdn.meta.ua/meta_news/bb/01000leu-bb4e_1280x720.jpeg",
            recipeLink = "https://t.me/obedkakdoma/274",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Нежнейшая куриная грудка в сливочном соусе",
            type = "Мясо/Рыба",
            imageUrl = "https://focus.ua/static/storage/originals/5/f1/e463c0917930396de5b26487273fff15.jpg",
            recipeLink = "https://t.me/obedkakdoma/275",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Запеканка с овощами и куриной грудкой",
            type = "Гарнир",
            imageUrl = "https://img.iamcook.ru/old/upl/recipes/cat/u-b3aabb37106a0023996c8346d02befad.JPG",
            recipeLink = "https://t.me/obedkakdoma/276",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Куриные крылья в соево-медовом соусе",
            type = "Мясо/Рыба",
            imageUrl = "https://klopotenko.com/wp-content/uploads/2022/07/kyrinye-krylyshki-v-medovom-souse_sitewebru-1000x600.jpg?v=1720548571",
            recipeLink = "https://t.me/obedkakdoma/277",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Фрикадельки в сметанном соусе",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/7a/0c/54459/frikadelki-v-smetannom-souse-na-skovorode_1620976746_15_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/278",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Cочные рулетики в беконе",
            type = "Мясо/Рыба",
            imageUrl = "https://i.ytimg.com/vi/WkKUZLRk6Mo/maxresdefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/279",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Куриная грудка",
            type = "Мясо/Рыба",
            imageUrl = "https://i.ytimg.com/vi/11c28SX9dPA/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLA_spHhXMYZNeMAMuY7OInyESHLcg",
            recipeLink = "https://t.me/obedkakdoma/280",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Пикантная курочка в трёх соусах",
            type = "Мясо/Рыба",
            imageUrl = "https://kurica2.ru/wp-content/uploads/2022/07/0-kuritsa-po-koreyski.jpg",
            recipeLink = "https://t.me/obedkakdoma/282",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Сосиски в тесте",
            type = "Закуски",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/8c/f9/64870/sosiski-v-drojjevom-teste-v-duxovke_1652452027_8_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/283",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Котлетки",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/11/ec/40812/kurinye-kotlety-na-skovorode_1607709339_9_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/284",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Котлетки с сыром в сливочном соусе",
            type = "Мясо/Рыба",
            imageUrl = "https://i.ytimg.com/vi/jLf7IEqj69w/sddefault.jpg?v=65a01718",
            recipeLink = "https://t.me/obedkakdoma/286",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Запеченная грудка",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/0a/18/29112/kurinaya-grudka-zapechennaya-v-folge-v-duxovke_1611643581_18_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/288",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Фрикадельки в сметанном соусе",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/d4/b6/35417/frikadelki-v-smetannom-souse-v-duxovke_1622786451_13_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/290",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Линивые отбивные с сыром и со сметаной",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/img/content/20101/lenivye-otbivnye_1492883584_4_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/291",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Домашние колбаски с сыром",
            type = "Мясо/Рыба",
            imageUrl = "https://clutch.net.ua/crops/950469/640x480/2/0/2023/10/17/D8oyp5a7YNoOGXrKG6Z3hwLXhR2USGvbDuSWtHkH.jpg.webp",
            recipeLink = "https://t.me/obedkakdoma/293",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Рулетики с грибной начинкой",
            type = "Мясо/Рыба",
            imageUrl = "https://i.ytimg.com/vi/htAPIgpB_YQ/sddefault.jpg",
            recipeLink = "https://t.me/obedkakdoma/294",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Котлетки в панировке",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/b9/fa/34103/kotlety-v-panirovochnyx-suxaryax_1604319428_9_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/295",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Котлеты по Киевски",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/df/25/51020/kotlety-po-kievski-iz-kurinogo-farsha_1616069228_18_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/296",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "КУРИНЫЙ ШНИЦЕЛЬ",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/res/640/img/content/14301/shnicel-v-duxovke_1445074345_0_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/300",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Курочка в сыре",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/33/9c/38293/kurinoe-file-s-syrom-na-skovorode_1689479119_8_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/302",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Куриные колбаски",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/res/640/img/content/15707/kurinye-sosiski_1459875407_0_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/304",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Домашние колбаски",
            type = "Мясо/Рыба",
            imageUrl = "https://static.1000.menu/res/640/img/content-v2/9e/5b/59829/kolbasa-v-multivarke_1635346820_13_max.jpg",
            recipeLink = "https://t.me/obedkakdoma/305",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Курица «Веллингтон»",
            type = "Мясо/Рыба",
            imageUrl = "https://i.ytimg.com/vi/l2-5E4Q84zM/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCD26RVkafyEmKH4-Ntnp6kK3CtOg",
            recipeLink = "https://t.me/obedkakdoma/306",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Сочная грудка с сырной начинкой",
            type = "Мясо/Рыба",
            imageUrl = "https://lafoy.ru/photo_l/foto-2910-9.jpg",
            recipeLink = "https://t.me/obedkakdoma/308",
            isFavorite = false,
        ),
        Dish(
            id = idNumber++,
            name = "Курочка по - китайски",
            type = "Мясо/Рыба",
            imageUrl = "https://img.cookorama.net/uploads/images/00/20/62/2015/09/12/63d214_780x.jpg",
            recipeLink = "https://t.me/obedkakdoma/309",
            isFavorite = false,
        ),
    )
